name: CI with Minikube

on:
  push:
    branches:
      - main

jobs:
  minikube-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/v1.25.2/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.22.3/bin/linux/amd64/kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          sudo chmod +x /usr/local/bin/kubectl

      - name: Apply Kubernetes resources
        run: kubectl apply -f deploy/k8s.yaml
